### ISSUE TITLE
Update codeception/codeception to version 5

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#11664]
### Improvement description

Version 5 Supports Symfony >=4.4.24 <7.0

**Comment by fashxp** [comment]
**needs to wait until Pimcore 11**
- codeception 5 is not released yet
- cannot upgrade without BC break
  - namespace of test class changed `Codeception\TestCase\Test` --> `Codeception\Test\Unit` ??
  - some signature changes

#### TODOs: 
- [ ] Update to correct parent class in https://github.com/pimcore/pimcore/blob/10.x/tests/_support/Test/TestCase.php#L18
- [ ] Add additional abstract methods to test class in https://github.com/pimcore/pimcore/blob/10.x/tests/_support/Test/TestCase.php
- [ ] Update signature of `addNamespace` in https://github.com/pimcore/pimcore/blob/10.x/tests/_support/Util/Autoloader.php#L24
- [ ] Add type to `$config` here https://github.com/pimcore/pimcore/blob/10.x/tests/_support/Helper/AbstractDefinitionHelper.php#L27
- [ ] fix usages of `$tester`? 
- [ ] fix usages of Stub
