### ISSUE TITLE
[Bug][Permissions][Elements] IsAllowed does not consider main permissions but only workspace permissions

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12076]
### Expected behavior

When user does not have permission for `objects`, `assets` and `documents` it must not be able to access the corresponding elements, even it if has workspaces configured. 

### Actual behavior

User has access to elements as soon as there is a workspace configured - regardless the main permissions. 

### Steps to reproduce

- Create user with object workspace, but not assign it `objects` permission
- Call `isAllowed` on an object that is in the configured workspace --> will return `true`. 

## TODOs
- [x] add check to `isAllowed` in `AbstractElement`
- [x] Update tests , e.g. add `isAllowed` tests for `userPermissionTest6` in `ModelDataObjectPermissionsTest`
- [x] Add note in upgrade notes
