### ISSUE TITLE
Follow-up: disabled dnd in tree for objects with manual indexes

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12597]
### Improvement description

Details see https://github.com/pimcore/pimcore/pull/12555#issuecomment-1175900643

## TODOs
- [x] disable d&d for folders that have sort by index (manual) activated and are paginated only (not for all paginated folders)
- [x] don't allow to activate sorting by index (manual) for paginated folders 
- [x] make error message more specific, it should tell you the actual reason

![image](https://user-images.githubusercontent.com/8792145/177511393-7a4de38b-a6ba-42c6-a1ec-ec94e0229e3c.png)

**Comment by dvesh3** [comment]
Fixed by #12602
