### ISSUE TITLE
Replace Request::get with explicit input sources

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#14138]
### Improvement description

In Symfony 5.4, `Request::get()` was marked as internal and we should switch to `$request->attributes->get()` or `$request->query->get()` calls.

see more details https://symfony.com/blog/new-in-symfony-5-4-controller-changes
```[tasklist]
### Tasks
- [ ] https://github.com/pimcore/asset-metadata-class-definitions/pull/191
- [ ] https://github.com/pimcore/data-hub/pull/874
- [ ] https://github.com/pimcore/data-hub-file-export/pull/161
- [ ] https://github.com/pimcore/web-to-print-bundle/pull/86
- [ ] https://github.com/pimcore/newsletter-bundle/pull/54
- [ ] https://github.com/pimcore/data-hub-productsup/pull/110
- [ ] https://github.com/pimcore/output-data-config-toolkit/pull/124
- [ ] https://github.com/pimcore/payment-provider-mpay24-seamless/pull/16
- [ ] https://github.com/pimcore/data-hub-simple-rest/pull/162
- [ ] https://github.com/pimcore/statistics-explorer/pull/101
- [ ] https://github.com/pimcore/openid-connect/pull/109
- [ ] https://github.com/pimcore/object-merger/pull/52
- [ ] https://github.com/pimcore/advanced-object-search/pull/268
- [ ] https://github.com/pimcore/customer-data-framework/issues/408
- [ ] https://github.com/pimcore/headless-documents/issues/107
- [ ] https://github.com/pimcore/translations-provider-interfaces/issues/110
- [ ] https://github.com/pimcore/workflow-designer/issues/58
- [ ] https://github.com/pimcore/web2print-tools/issues/56
- [ ] https://github.com/pimcore/demo-enterprise/issues/91
- [ ] https://github.com/pimcore/demo/issues/405
- [ ] https://github.com/pimcore/perspective-editor/issues/114
- [ ] https://github.com/pimcore/pimcore/pull/17873
- [ ] https://github.com/pimcore/admin-ui-classic-bundle/issues/771
- [ ] https://github.com/pimcore/backend-power-tools-bundle/issues/443
```

**Comment by brusch** [comment]
Partly resolved by #13981

**Comment by jdreesen** [comment]
Was it intentional to close this?

**Comment by kingjia90** [comment]
@jdreesen ops no, as this is more a collecting list and it's not fully completed yet. Thank you for the heads-up
