### ISSUE TITLE
Refactor Bootstrap: remove autoloading for dynamic dataobject classes

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#14485]
### Task description
Related to https://github.com/pimcore/pimcore/issues/10344

- [x] Remove including autoload files in `bootstrap()` after https://github.com/pimcore/skeleton/pull/128/files is merged.
- [x]  Remove `setAutoloader`, `getAutoloader` & `autoload` methods from Bootstrap.php as these methods are used to dynamically autoload dataobject classes from var directory(or custom var directory) which should be handled in project `composer.json` (add docs [here](https://github.com/pimcore/pimcore/blob/543457a81d2171174f277677ea7e20e25b7ff6c3/doc/Development_Documentation/01_Getting_Started/03_Configuration.md#L63)).
- [x] Remove unused constant `PIMCORE_APP_BUNDLE_CLASS_FILE`
