### ISSUE TITLE
Document Editables: New concept for saving nested editables

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1467]
Requirements: 
- Flag to choose the flattening mode (for backward compatibility) see: https://github.com/pimcore/pimcore/blob/dffcbfeaa805227cf610ed9d4a1eead66f1ea8be/app/config/config.yml#L11-L11
- Default should be the new scheme
- Easy to understand flattening scheme (maybe a `.` notation?) 
- Generated editable identifiers should be as short as possible (remember 750 byte length) 
- Fixes #559 

Requirements:

- [x] copy a element from a nested area into root
- [x] copy a element from root into a nested area
- [x] copy a nested element into a nested area
- [x] copy a root element with a arbitrary amount of child areas to root
- [x] copy a nested element with a arbitrary amount of child areas into another nested area

**Comment by solverat** [comment]
O.M.G 🎉 

:)

**Comment by brusch** [comment]
ToDo: Docs
- Note in upgrade notes and how to configure the legacy naming strategy  

Migration: 
- see #1525

**Comment by maff** [comment]
**TODO**: Update `getElement()` to support new naming scheme - see #1535

**Comment by maff** [comment]
@solverat could you check your copy/paste test cases with a build >= 56? I tested your list from issue #559, but just to make sure. Please note that copy/paste only works for the new naming scheme as of build 54 and there is no migration from old to new yet.

**Comment by solverat** [comment]
hey @maff. i'm just back from japan, couldn't get back to this sooner. i'll check it as soon as i can although you already closed this ticket.
