### ISSUE TITLE
[Task]: Check and remove class_aliases in 11.x 

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14739]
### Task description

We should not use class_aliases in 11.x for non existing classes.

Remove all class_aliases and move them to dedicated repository: https://github.com/pimcore/compatability-bridge

- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/ApplicationLoggerBundle/src/Maintenance/LogArchiveTask.php#L138
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/ApplicationLoggerBundle/src/ApplicationLogger.php#L414
- [x]  https://github.com/pimcore/pimcore/blob/11.x/bundles/ApplicationLoggerBundle/src/Maintenance/LogMailMaintenanceTask.php#L98
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/ApplicationLoggerBundle/src/FileObject.php#L73
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/ApplicationLoggerBundle/src/Processor/ApplicationLoggerProcessor.php#L149
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/ApplicationLoggerBundle/src/Handler/ApplicationLoggerDb.php#L96
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/ApplicationLoggerBundle/src/Controller/LogController.php#L275
- [x] https://github.com/pimcore/pimcore/blob/11.x/phpstan-bootstrap.php#L27
- [x] https://github.com/pimcore/pimcore/blob/11.x/models/Version.php#L294
- [x] https://github.com/pimcore/pimcore/blob/11.x/bundles/PersonalizationBundle/src/Model/Tool/Targeting/TargetGroup.php#L166

**Comment by lukmzig** [comment]
Based on the internal discussion we decided to keep these aliases for now, mainly because we need to keep the compatibility in the bundles for 10.6 and 11.x

**Comment by brusch** [comment]
But the alias doesn't help if you request the old class name, because the autoloader can't find them ... so basically they are useless unless you require the new class name first ...
