### ISSUE TITLE
Pimcore 11 - Pre-Release Todo's 

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14913]
### Improvement description

- [ ] composer.json: remove `"minimum-stability": "dev"` from all packages (skeleton, demos, bundles, ...) 
- [ ] Remove  `COMPOSER_ROOT_VERSION` workflow configs in pimcore/pimcore repo, added by [this commit
](https://github.com/pimcore/pimcore/pull/14908/commits/580e907508f151c93ae095f7eb7e0888b1275ff0)
- [ ] remove pimcore/* requirement conflicts from all packages (skeleton, demos, bundles, ...)
