### ISSUE TITLE
Separating Documents Settings tab for Meta (SEO) fields and other advanced fields such as Controller and Action

### ISSUE THREAD

**Issue by kovinet** [pimcore/pimcore#2576]
# Bug Report
## Please make sure all the following boxes are checked before submitting your issue - thank you!
- [X] This is not a security issue / vulnerability -> send them to security@pimcore.org instead
- [X] Behavior is reproducible on http://demo.pimcore.org/admin/ (admin/demo) 
or on a clean install of the latest build (out of your project, to avoid problems with custom code, plugins, ...) 
- [X] You're not able to fix the problem yourself and send us a pull request instead of an issue. 
- [X] There's no existing ticket for the same issue
- [X] Remove unused sections from below and this bullet points

# Feature Request 
## Please make sure all the following boxes are checked before submitting your feature request - thank you!
- [X] There is no existing issue regarding the same topic

## Feature description 
As suggested [on forum](https://talk.pimcore.org/t/hide-controller-action-template-options-while-allowing-title-description-metadata/434) I have always disliked that for Documents in Settings tab you have at the same time basic things like Title, Description and other Meta tag management as well as more advanced settings such as choosing Controller and Action. Since most content editors need to enter Title and Description I would prefer to hide to them the form for choosing controller and action. Since they never know what to do with it and playing with it will probably break something.

My suggestion would be to somehow separate these two. Either with having new tab for "SEO" or adding extra option to permission management to only allow seeing part of Settings tab.

I am aware of "SEO Document Editor" which allows you to edit Meta tags globally, but it would still be convenient to be able to edit Meta data without allowing to also change controller directly while edinting docuent - in my opinion.

**Comment by Cruiser13** [comment]
I'd actually prefer a permission setting instead of yet another tab.

**Comment by brusch** [comment]
I agree with @Cruiser13 ... we should avoid another tab.
