### ISSUE TITLE
[Core] Replace all existing asynchronous queues with Symfony Messenger

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#6371]
- [x] Search Backend Data ( @dvesh3 #10423) 
- [x] System thumbnail generation / Asset updates ( @brusch #10390) (See also #10300)
- [x] Sanity Check ( @brusch #10439)
- [x] Version deletion( @dvesh3 #10451)
- [x] Image Optimizer (@dvesh3 #10461)
- [x] Web2Print (@dvesh3 #10455 )
- [x] Newsletter sending ( #10329 )
- [x] Video transcoding ( #10329 )
- [x] Thumbnail cleanup ( #10383 )

See also #9810

**Comment by brusch** [comment]
See also #10329

**Comment by dpfaffenbauer** [comment]
- Search Backend Data

**Comment by dpfaffenbauer** [comment]
- Cache::shutdown maybe?

**Comment by blankse** [comment]
- System thumbnail generation (See https://github.com/pimcore/pimcore/pull/10300)

**Comment by jdreesen** [comment]
I think this was closed by mistake from #10423.

**Comment by brusch** [comment]
@dvesh3 Version delete see: #9755

**Comment by brusch** [comment]
Alright, seems we are done here for now 😊🎉 (more to come 😉)
